version: "3.9"
name: task-tracker-rjs-net
services:
  frontend:
    build:
      context: ../src/task-tracker-web-ui
  frontend-dapr:
    image: "daprio/daprd:1.9.4"
    network_mode: "service:frontend"
    depends_on:
      - frontend
  backend:
    build:
      context: ../src/task-tracker-web-api
  backend-dapr:
    image: "daprio/daprd:1.9.4"
    network_mode: "service:backend"
    depends_on:
      - backend
  envoy:
    build: ../infrastructure/envoy
    depends_on:
      - backend
  envoy-dapr:
    image: "daprio/daprd:1.9.4"
    network_mode: "service:envoy"
    depends_on:
      - envoy
  dapr-placement:
    image: "daprio/dapr:1.9.4"