version: "3.9"
name: task-tracker-rjs-net
services:
  frontend:
    environment:
      API_URL: http://localhost:3500/api
    volumes:
      - type: bind
        source: ./web-ui.app.config.json
        target: /usr/share/nginx/html/assets/app.config.json
      - ./templates:/etc/nginx/templates
    ports:
      - "3000:80"
  #    - "3501:3501"
  frontend-dapr:
    command: [ "./daprd",
               "-app-id", "task-tracker-web-ui",
               "-app-port", "80",
               "-app-protocol", "http",
               "-dapr-http-port", "3501"
    ]
  #backend:
  #  ports:
  #    - "5254:80"
  #    - "3502:3502"
  backend-dapr:
    command: [ "./daprd",
               "-app-id", "task-tracker-web-api",
               "-app-port", "80",
               "-app-protocol", "http",
               "-dapr-http-port", "3502"
    ]
  envoy:
    ports:
      - "8080:80"
      - "8001:8001"
    volumes:
      - ./templates/envoy.yaml:/config/envoy.yaml
    environment:
      - DEBUG_LEVEL=debug
      - TASK_SERVICE_NAME=backend
      - TASK_SERVICE_PORT=80
  envoy-dapr:
    command: [ "./daprd",
               "-app-id", "webapigw",
               "-app-port", "80"
    ]
  dapr-placement:
    command: [ "./placement", "-port", "50000", "-log-level", "debug" ]
    ports:
      - "50000:50000"